version: '3.8'
services:
  ubuntu:
    build:
      context: .
    container_name: ubuntu
    volumes:
      - "./workspace:/root/workspace"
      - "~/.vimrc:/root/.vimrc"
      - "~/.vim:/root/.vim"
